name: meal_task_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  auto_route: ^10.1.0+1
  build_runner: ^2.4.15
  dio: ^5.9.1
  easebuzz_flutter: ^0.0.7
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  gap: ^3.0.1
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  google_maps_flutter: ^2.14.2
  google_sign_in: ^6.2.2
  riverpod_annotation: ^2.6.1
  riverpod_generator: ^2.6.5
  shared_preferences: ^2.5.3
  flutter_svg: ^2.0.10
  firebase_core: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  auto_route_generator: ^10.0.1
  flutter_gen_runner: ^5.10.0
  build_runner: ^2.4.15

flutter:
  uses-material-design: true

  assets:
    - assets/svg/google.svg

flutter_gen:
  output: lib/src/shared/gen/ 
  line_length: 80 

  integrations:
    flutter_svg: true
    
    lottie: true

